FROM playniuniu/jupyter-octave:latest

MAINTAINER tuanna47@fpt.com.vn


COPY jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py

VOLUME /opt/
EXPOSE 8888

CMD ["/env/bin/jupyter", "notebook", "--allow-root"]
